export type TypographyVariant = 'sm' | 'smBold' | 'base' | 'baseBold' | 'lg' | 'lgBold' | 'lgXBold'

export type IconName =
  | 'arrowBottom'
  | 'arrowLeft'
  | 'bookmarkFill'
  | 'bookmark'
  | 'composeTweet'
  | 'composeMessage'
  | 'emoji'
  | 'explore'
  | 'explorerFill'
  | 'gif'
  | 'homeFill'
  | 'home'
  | 'like'
  | 'listsFill'
  | 'listsAdd'
  | 'lists'
  | 'media'
  | 'messagesFill'
  | 'messages'
  | 'more'
  | 'moreWithCircle'
  | 'notificationFill'
  | 'notification'
  | 'options'
  | 'profileFill'
  | 'profile'
  | 'question'
  | 'reply'
  | 'retweet'
  | 'search'
  | 'searchFocused'
  | 'share'
  | 'spark'
  | 'twitter'
  | 'x'
